name: Get 0G Storage Base URI

# این ورک‌فلو فقط به صورت دستی اجرا می‌شود
on:
  workflow_dispatch:

jobs:
  get-uri-job:
    runs-on: ubuntu-latest
    steps:
      # ۱. کد ریپازیتوری را دانلود می‌کند
      - name: Checkout repository
        uses: actions/checkout@v4

      # ۲. محیط Go را راه‌اندازی می‌کند
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # ۳. وابستگی‌های لازم را بر اساس مستندات رسمی نصب می‌کند
      - name: Initialize and Install Dependencies
        run: |
          # ماژول Go را راه‌اندازی می‌کند
          go mod init geturi
          # پکیج‌های رسمی و صحیح را نصب می‌کند
          go get github.com/0glabs/0g-storage-client
          go get github.com/ethereum/go-ethereum
          # تمام وابستگی‌ها را همگام‌سازی می‌کند
          go mod tidy

      # ۴. اسکریپت Go را برای دریافت آدرس اجرا می‌کند
      - name: Run the script to get URI
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: go run get_base_uri.go

