name: Get 0G Storage Base URI

on:
  workflow_dispatch:

jobs:
  get-uri-job:
    runs-on: ubuntu-latest
    steps:
      # ۱. نصب پیش‌نیازها
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # ۲. دانلود سورس کد رسمی 0g-storage-client
      - name: Clone Official 0G Storage Client Repository
        uses: actions/checkout@v4
        with:
          repository: 0glabs/0g-storage-client
          path: 0g-storage-client

      # ۳. ساخت (Build) فایل اجرایی CLI
      - name: Build the CLI Binary
        run: |
          cd 0g-storage-client
          go build
          mv 0g-storage-client ../zg_storage

      # ۴. آپلود فایل تستی با استفاده از CLI ساخته شده
      - name: Upload Test File and Get Root Hash
        id: upload_step
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "Creating a temporary test file..."
          echo "This is the final test file." > testfile.txt
          
          echo "Uploading the file using the official CLI..."
          
          UPLOAD_OUTPUT=$(./zg_storage upload \
            --url "https://evmrpc-testnet.0g.ai" \
            --indexer "https://indexer-storage-testnet-turbo.0g.ai" \
            --key "$PRIVATE_KEY" \
            --file ./testfile.txt | tee /dev/stderr)
          
          # --- دستور استخراج هش در اینجا اصلاح شده است ---
          # به جای "Root hash" به دنبال "root =" می‌گردد
          ROOT_HASH=$(echo "$UPLOAD_OUTPUT" | grep "file uploaded, root =" | awk '{print $NF}')
          echo "Extracted Root Hash: $ROOT_HASH"
          
          # ذخیره کردن هش برای استفاده در مرحله بعد
          echo "ROOT_HASH=$ROOT_HASH" >> $GITHUB_OUTPUT

      # ۵. نمایش هش نهایی به عنوان خروجی اصلی
      - name: Display the Final Identifier
        run: |
          echo "======================================================================"
          echo "✅ Success! Your File Identifier (Merkle Root Hash) is:"
          echo "${{ steps.upload_step.outputs.ROOT_HASH }}"
          echo "======================================================================"
          echo "NOTE: This hash is the unique ID for your uploaded data."
          echo "For your contract's baseURI, you will likely use a gateway URL followed by this hash."
