name: Get 0G Storage Base URI

on:
  workflow_dispatch:

jobs:
  get-uri-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- مرحله نهایی و اصلاح شده برای حل مشکل ناسازگاری ---
      - name: Initialize and Configure Go Module
        run: |
          # ۱. ماژول Go را راه‌اندازی می‌کند
          echo "Initializing Go module..."
          go mod init geturi

          # ۲. نسخه‌های دقیق و سازگار پکیج‌ها را به صورت دستی مشخص می‌کند
          echo "Forcing specific compatible package versions..."
          go mod edit -require=github.com/0glabs/0g-storage-client@v0.4.1
          go mod edit -require=github.com/ethereum/go-ethereum@v1.13.5

          # ۳. تمام وابستگی‌ها را بر اساس نسخه‌های مشخص شده، همگام‌سازی می‌کند
          echo "Tidying and syncing all module dependencies..."
          go mod tidy

      - name: Run the script to get URI
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: go run get_base_uri.go

