name: Get 0G Storage Base URI

on:
  workflow_dispatch:

jobs:
  get-uri-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # --- مرحله جدید و اصلاح شده ---
      - name: Initialize Go module and Install Dependencies
        run: |
          # ابتدا یک ماژول Go را راه‌اندازی می‌کند تا دستورات بعدی کار کنند
          echo "Initializing Go module..."
          go mod init geturi

          # سپس کتابخانه‌های رسمی مورد نیاز را نصب می‌کند
          echo "Installing 0G Storage and Ethereum libraries..."
          go get github.com/0glabs/0g-storage-client
          go get github.com/ethereum/go-ethereum

      - name: Run the script to get URI
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: go run get_base_uri.go

